name = "auth-hook-react-email-resend"
main = "index.js"
compatibility_date = "2024-08-17"

[vars]
FROM_EMAIL = "noreply@royalequips.com"

# Environment variables (set via wrangler secret put)
# RESEND_API_KEY
# BIGQUERY_PROJECT_ID  
# BIGQUERY_TOKEN
# WEBHOOK_URL
# SENTRY_DSN

[[kv_namespaces]]
binding = "AUTH_KV"
id = "auth_verification_store"