version: "3.8"

services:
  orchestrator:
    build: .
    container_name: royal-equips-orchestrator
    environment:
      # Replace these with your actual Shopify and OpenAI credentials
      SHOPIFY_API_KEY: "${SHOPIFY_API_KEY}"
      SHOPIFY_API_SECRET: "${SHOPIFY_API_SECRET}"
      SHOP_NAME: "${SHOP_NAME}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    ports:
      - "8000:8000"
    restart: unless-stopped
  command-center:
    build:
      context: .
      dockerfile: admin/Dockerfile
    container_name: royal-equips-command-center
    environment:
      VITE_API_URL: "http://localhost:8000"
      VITE_WEBSOCKET_URL: "ws://localhost:8000/ws"
    ports:
      - "3000:3000"
    depends_on:
      - orchestrator
    restart: unless-stopped