# Render configuration for deploying Royal Equips Orchestrator
services:
  # FastAPI API
  - type: web
    name: orchestrator-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOP_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BIGQUERY_PROJECT_ID
        sync: false
      - key: BIGQUERY_DATASET
        sync: false
      - key: BIGQUERY_TABLE
        sync: false

  # Streamlit control center
  - type: web
    name: control-center
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    # For Docker services use dockerCommand to override CMD
    dockerCommand: >
      streamlit run orchestrator/control_center/app.py
      --server.address=0.0.0.0 --server.port=$PORT
      --server.enableCORS=false --server.headless=true
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOP_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BIGQUERY_PROJECT_ID
        sync: false
      - key: BIGQUERY_DATASET
        sync: false
      - key: BIGQUERY_TABLE
        sync: false

  # Daily analytics export at 03:00 UTC
  - type: cron
    name: export-analytics
    env: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 3 * * *"
    dockerCommand: >
      python scripts/run_analytics.py
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOP_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BIGQUERY_PROJECT_ID
        sync: false
      - key: BIGQUERY_DATASET
        sync: false
      - key: BIGQUERY_TABLE
        sync: false

  # Daily security scan at 02:00 UTC
  - type: cron
    name: security-scan
    env: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 2 * * *"
    dockerCommand: >
      python scripts/run_security_checks.py
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOP_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BIGQUERY_PROJECT_ID
        sync: false
      - key: BIGQUERY_DATASET
        sync: false
      - key: BIGQUERY_TABLE
        sync: false
