# Wrangler v4 configuration
# Deploy command: wrangler deploy -e <environment> (e.g., -e production)
name = "royal-equips-orchestrator"
main = "src/index.js"
compatibility_date = "2025-08-10"

[observability.logs]
enabled = true

# Default environment variables (used when no specific environment is targeted)
[vars]
PYTHON_API_URL = "https://royal-equips-orchestrator.onrender.com"

# Staging environment configuration
[env.staging]
name = "royal-equips-orchestrator-staging"

[env.staging.vars]
PYTHON_API_URL = "https://royal-equips-orchestrator-staging.onrender.com"

# Production environment configuration  
[env.production]
name = "royal-equips-orchestrator"

[env.production.vars]
PYTHON_API_URL = "https://royal-equips-orchestrator.onrender.com"
