# Wrangler v4 configuration
name = "royal-equips-orchestrator"
main = "src/index.js"
compatibility_date = "2025-08-10"

[observability.logs]
enabled = true

# Backend API base URL; override per-environment if needed
[vars]
PYTHON_API_URL = "https://royal-equips-orchestrator.onrender.com"

[env.production]
name = "royal-equips-orchestrator"

[env.production.vars]
PYTHON_API_URL = "https://royal-equips-orchestrator.onrender.com"
