"""Initial platform schema with comprehensive models

Revision ID: 62f8ecaeb262
Revises: 
Create Date: 2025-09-26 23:42:25.779395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62f8ecaeb262'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_agent', sa.String(length=100), nullable=False),
    sa.Column('to_agent', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_from_agent'), 'agent_messages', ['from_agent'], unique=False)
    op.create_index('ix_agent_messages_from_to', 'agent_messages', ['from_agent', 'to_agent'], unique=False)
    op.create_index(op.f('ix_agent_messages_status'), 'agent_messages', ['status'], unique=False)
    op.create_index('ix_agent_messages_status_priority', 'agent_messages', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_agent_messages_to_agent'), 'agent_messages', ['to_agent'], unique=False)
    op.create_index('ix_agent_messages_topic', 'agent_messages', ['topic'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index('ix_agent_runs_agent_status', 'agent_runs', ['agent_name', 'status'], unique=False)
    op.create_index('ix_agent_runs_started_at', 'agent_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopify_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('accepts_marketing', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('lifetime_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index('ix_customers_shopify_id', 'customers', ['shopify_id'], unique=False)
    op.create_index('ix_customers_total_spent', 'customers', ['total_spent'], unique=False)
    op.create_table('inventory_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=50), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'inventory_item_id')
    )
    op.create_index(op.f('ix_inventory_levels_inventory_item_id'), 'inventory_levels', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_location_id'), 'inventory_levels', ['location_id'], unique=False)
    op.create_index('ix_inventory_levels_location_item', 'inventory_levels', ['location_id', 'inventory_item_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopify_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_index(op.f('ix_products_shopify_id'), 'products', ['shopify_id'], unique=True)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_index('ix_products_updated_at', 'products', ['updated_at'], unique=False)
    op.create_table('research_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_keyword', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('competition_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_potential', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('researched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_date', 'research_history', ['researched_at'], unique=False)
    op.create_index(op.f('ix_research_history_product_keyword'), 'research_history', ['product_keyword'], unique=False)
    op.create_index('ix_research_keyword', 'research_history', ['product_keyword'], unique=False)
    op.create_index('ix_research_priority', 'research_history', ['priority_score'], unique=False)
    op.create_index('ix_research_source', 'research_history', ['source'], unique=False)
    op.create_table('webhook_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('shopify_event_id', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_outbox_received_at', 'webhook_outbox', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_shopify_event_id'), 'webhook_outbox', ['shopify_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_outbox_status'), 'webhook_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_topic'), 'webhook_outbox', ['topic'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopify_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_discounts', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financial_status', sa.String(length=20), nullable=False),
    sa.Column('fulfillment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_financial_status', 'orders', ['financial_status'], unique=False)
    op.create_index(op.f('ix_orders_shopify_id'), 'orders', ['shopify_id'], unique=True)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('shopify_id', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('inventory_item_id', sa.String(length=50), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=True),
    sa.Column('inventory_policy', sa.String(length=20), nullable=True),
    sa.Column('option1', sa.String(length=100), nullable=True),
    sa.Column('option2', sa.String(length=100), nullable=True),
    sa.Column('option3', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_variants_inventory_item_id'), 'product_variants', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_product_variants_shopify_id'), 'product_variants', ['shopify_id'], unique=True)
    op.create_index('ix_variants_inventory_item_id', 'product_variants', ['inventory_item_id'], unique=False)
    op.create_index('ix_variants_shopify_id', 'product_variants', ['shopify_id'], unique=False)
    op.create_index('ix_variants_sku', 'product_variants', ['sku'], unique=False)
    op.create_table('order_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('shopify_line_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('variant_title', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_line_items_order_id', 'order_line_items', ['order_id'], unique=False)
    op.create_index('ix_line_items_shopify_line_id', 'order_line_items', ['shopify_line_id'], unique=False)
    op.create_index('ix_line_items_variant_id', 'order_line_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_shopify_line_id'), 'order_line_items', ['shopify_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_line_items_shopify_line_id'), table_name='order_line_items')
    op.drop_index('ix_line_items_variant_id', table_name='order_line_items')
    op.drop_index('ix_line_items_shopify_line_id', table_name='order_line_items')
    op.drop_index('ix_line_items_order_id', table_name='order_line_items')
    op.drop_table('order_line_items')
    op.drop_index('ix_variants_sku', table_name='product_variants')
    op.drop_index('ix_variants_shopify_id', table_name='product_variants')
    op.drop_index('ix_variants_inventory_item_id', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_shopify_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_inventory_item_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_orders_shopify_id'), table_name='orders')
    op.drop_index('ix_orders_financial_status', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_webhook_outbox_topic'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_status'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_shopify_event_id'), table_name='webhook_outbox')
    op.drop_index('ix_webhook_outbox_received_at', table_name='webhook_outbox')
    op.drop_table('webhook_outbox')
    op.drop_index('ix_research_source', table_name='research_history')
    op.drop_index('ix_research_priority', table_name='research_history')
    op.drop_index('ix_research_keyword', table_name='research_history')
    op.drop_index(op.f('ix_research_history_product_keyword'), table_name='research_history')
    op.drop_index('ix_research_date', table_name='research_history')
    op.drop_table('research_history')
    op.drop_index('ix_products_updated_at', table_name='products')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index(op.f('ix_products_shopify_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_inventory_levels_location_item', table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_location_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_inventory_item_id'), table_name='inventory_levels')
    op.drop_table('inventory_levels')
    op.drop_index('ix_customers_total_spent', table_name='customers')
    op.drop_index('ix_customers_shopify_id', table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_started_at', table_name='agent_runs')
    op.drop_index('ix_agent_runs_agent_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_agent_messages_topic', table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_to_agent'), table_name='agent_messages')
    op.drop_index('ix_agent_messages_status_priority', table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_status'), table_name='agent_messages')
    op.drop_index('ix_agent_messages_from_to', table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_from_agent'), table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
