name: CI
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "20"

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # actions/checkout@v4

      # Set git user identity for any git operations
      - name: Set git user identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Setup Node.js and pnpm (with caching)
      - name: Setup Node + pnpm
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      # Enable and prepare pnpm for reproducible builds
      - run: corepack enable
      - run: corepack prepare pnpm@9.9.0 --activate

      # Install dependencies (no lifecycle scripts for CI safety)
      - name: Install deps (no scripts)
        run: pnpm install --ignore-scripts --frozen-lockfile
        env:
          HUSKY: 0

      # Lint source code only (exclude artifacts)
      - name: Lint
        run: pnpm lint

      # Type checking (strict TypeScript)
      - name: Typecheck
        run: pnpm typecheck

      # Run tests with JUnit reporter for CI integration
      - name: Test
        run: pnpm test -- --ci --reporters=default --reporters=jest-junit

      # (Optional) Debug: List JUnit report files
      - name: Check JUnit reports directory
        run: ls -l reports/junit || echo "JUnit report directory missing"

      # Upload JUnit XML results for reporting (always, even on failure)
      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # actions/upload-artifact@v4
        with:
          name: junit
          path: reports/junit/junit.xml
          if-no-files-found: ignore
