name: Commitlint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Enterprise: Use latest stable version, pin exact commit for supply chain security
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for audit/revert

      # Setup Node.js (exact version for reproducibility)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1' # Pin exact version

      # Self-healing install: If npm ci fails (lockfile mismatch), recover and update lockfile
      - name: Install dependencies (self-healing)
        shell: bash
        run: |
          set -e
          npm ci || (npm install && npm ci)

      # Lint commits in dynamic range, fail fast on errors, log structured output
      - name: Run commitlint with dynamic range and structured logs
        shell: bash
        run: |
          set -e
          OLDEST_COMMIT=$(git rev-list --max-count=50 HEAD | tail -1)
          npx commitlint --from=$OLDEST_COMMIT --to=HEAD | tee commitlint.log
          echo '{"event":"commitlint","range":"'$OLDEST_COMMIT'..HEAD"}' >> commitlint-events.json

      # Upload structured logs for audit compliance
      - name: Upload commitlint logs
        uses: actions/upload-artifact@v4
        with:
          name: commitlint-artifacts
          path: |
            commitlint.log
            commitlint-events.json
