name: Empire Orchestrator - Cross-Platform
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform'
        required: false
        default: 'windows'
        type: choice
        options:
        - windows
        - linux
        - both
permissions:
  contents: read
jobs:
  product_research:
    uses: ./.github/workflows/product-research.yml
    with:
      os: '["ubuntu-latest"]'
  order_processing:
    needs: [product_research]
    uses: ./.github/workflows/order-processing.yml
    with:
      os: '["ubuntu-latest"]'
  marketing_campaign:
    needs: [order_processing]
    uses: ./.github/workflows/marketing-campaign.yml
    with:
      os: '["ubuntu-latest"]'
