name = "royal-equips-proxy"
main = "worker.js"

# Update these with your actual domain and backend URL
routes = [
  { pattern = "your-domain.com/*", zone_name = "your-domain.com" }
]

[vars]
UPSTREAM = "https://api.your-backend.example"

# For development
[env.dev]
vars = { UPSTREAM = "http://localhost:10000" }

# For production  
[env.production]
vars = { UPSTREAM = "https://your-production-backend.render.com" }