#!/bin/bash
# ensure-runtime-logs.sh
# Ensures runtime log files always exist for artifact upload
# Fixes issue where workflows fail when expected log files are missing

set -e

RUNTIME_LOGS_DIR="/home/runner/work/_temp/runtime-logs"
BLOCKED_JSONL="$RUNTIME_LOGS_DIR/blocked.jsonl"
BLOCKED_MD="$RUNTIME_LOGS_DIR/blocked.md"

echo "🔍 Ensuring runtime logs directory exists..."

# Create runtime logs directory if it doesn't exist
mkdir -p "$RUNTIME_LOGS_DIR"

# Create blocked.jsonl if it doesn't exist
if [ ! -f "$BLOCKED_JSONL" ]; then
    echo "📝 Creating blocked.jsonl file..."
    cat > "$BLOCKED_JSONL" << 'EOF'
[]
EOF
    echo "✅ Created empty blocked.jsonl"
else
    echo "✅ blocked.jsonl already exists"
fi

# Create blocked.md if it doesn't exist
if [ ! -f "$BLOCKED_MD" ]; then
    echo "📝 Creating blocked.md file..."
    cat > "$BLOCKED_MD" << 'EOF'
# Runtime Logs - Blocked Events

## Summary
No blocked events detected during this runtime session.

**Generated:** $(date -u)
**Status:** All operations completed successfully
**Blocked Events:** 0

---
*Generated by Royal Equips Empire Runtime Logging System*
EOF
    echo "✅ Created blocked.md"
else
    echo "✅ blocked.md already exists"
fi

echo "🚀 Runtime logs directory prepared successfully!"
echo "   Directory: $RUNTIME_LOGS_DIR"
echo "   Files created: blocked.jsonl, blocked.md"