# Wrangler v4 configuration
# Deploy command: wrangler deploy -e <environment> (e.g., -e production)
name = "royal-equips-orchestrator"
main = "src/index.js"
compatibility_date = "2025-08-10"

[observability.logs]
enabled = true

# Default environment variables (used when no specific environment is targeted)
[vars]
UPSTREAM_API_BASE = "http://localhost:10000"
ALLOWED_ORIGINS = "*"

# Staging environment configuration
[env.staging]
name = "royal-equips-orchestrator-staging"

[env.staging.vars]
UPSTREAM_API_BASE = "https://aira-staging.internal:10000"
ALLOWED_ORIGINS = "https://staging.royalequips.com,https://command-center-staging.pages.dev"

# Production environment configuration  
[env.production]
name = "royal-equips-orchestrator"

[env.production.vars]
UPSTREAM_API_BASE = "https://aira.internal:10000"
ALLOWED_ORIGINS = "https://royalequips.com,https://command-center.pages.dev"
