name: auto-pr
on:
  push:
    branches-ignore: [master]

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR: ${{ github.ref_name }}"
          body: "Automated PR for branch `${{ github.ref_name }}`"
          base: master
          branch: auto/${{ github.ref_name }}
          delete-branch: true
          reviewers: Skidaw23
          # or: team-reviewers: Royal-Equips-Org/platform-admins
          labels: automerge

      - name: Enable auto-merge (squash)
        if: steps.create_pr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: SQUASH
