name: ☁️ Cloudflare Deploy

on:
  push:
    branches: [main, master]
    # Only trigger when these folders change (cannot combine with paths-ignore)
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'workers/**'
      - 'edge-functions/**'
    # NOTE: Cannot use paths-ignore here due to GitHub Actions limitation.
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

permissions:
  contents: read
  deployments: write

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "10.17.0"

jobs:
  deploy:
    name: 🚀 Deploy to Cloudflare
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398466c2d53 # v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: 🏗️ Install & Build
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm --filter "@royal-equips/command-center-ui" build
          # Verify functions are included in build
          ls -la apps/command-center-ui/dist/functions/api/webhooks/
        env:
          HUSKY: 0

      - name: 🌐 Deploy Command Center (Pages)
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: royal-equips-command-center
          directory: apps/command-center-ui/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚡ Deploy Workers
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: workers
          environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}

      - name: 🔗 Deploy Edge Functions
        run: |
          cd edge-functions/auth-hook-react-email-resend
          npx wrangler deploy --env ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

# --- END ---
