name: Commitlint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18' # Use v18 for best compatibility
      - run: npm ci
      - run: npx commitlint --from=HEAD~50 --to=HEAD
