name: Commitlint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Run commitlint with dynamic range
        shell: bash
        run: |
          # Get the oldest commit up to 50 back, avoiding error if fewer commits exist
          OLDEST_COMMIT=$(git rev-list --max-count=50 HEAD | tail -1)
          npx commitlint --from=$OLDEST_COMMIT --to=HEAD
