# .github/workflows/commitlint.yml
name: Commitlint
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - run: npm i -g @commitlint/{config-conventional,cli}@19
      - run: commitlint --from=HEAD~50 --to=HEAD
