name: Deploy to Render

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Only run if the deploy hook secret is configured
    if: ${{ secrets.RENDER_DEPLOY_HOOK_URL != '' }}
    
    steps:
    - name: Trigger Render Deploy
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    
    - name: Deploy Success
      run: |
        echo "✅ Render deployment triggered successfully"
        echo "Check your Render dashboard to monitor the deployment progress"