name: Empire Audit
on:
  push:
  pull_request:
  schedule: [ { cron: "0 */6 * * *" } ]
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  issues: write
  pull-requests: write
jobs:
  code-health:
    runs-on: ubuntu-latest
    strategy: { matrix: { node: [20] } }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v3
        with: { version: 9.9.0 }
      - uses: actions/setup-node@v4
        with: { node-version: ${{ matrix.node }}, cache: "pnpm" }
      - name: Install (no scripts)
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Lint
        run: pnpm -w eslint .
      - name: Type check (if tsconfig present)
        run: |
          if [ -f tsconfig.json ] || ls -1 **/tsconfig*.json 2>/dev/null; then pnpm -w tsc -b --pretty false; fi
      - name: Build (if present)
        run: |
          if [ -f package.json ] && jq -e '.scripts.build' package.json >/dev/null; then pnpm -w run build; fi
      - name: Unit tests (if present)
        run: |
          if [ -f package.json ] && jq -e '.scripts.test' package.json >/dev/null; then pnpm -w run test -- --ci --reporter=dot || true; fi
  codeql:
    uses: github/codeql-action/.github/workflows/codeql-analysis.yml@v3
    with: { languages: 'javascript,python,go', build-mode: none }
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-results.sarif }
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
  dep-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: pnpm/action-setup@v3
        with: { version: 9.9.0 }
      - run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Audit
        run: pnpm audit --json || true
