name: enforce-main-health
on:
  push:
    branches: [master]
permissions:
  contents: write
  pull-requests: write
jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.outcome.outputs.status }}
    steps:
      - uses: actions/checkout@v5

      # Install pnpm globally (production best practice)
      - name: Install pnpm
        run: npm install -g pnpm

      # Setup pnpm cache for faster installs
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies using pnpm and frozen lockfile for reproducible builds
      - name: Install dependencies
        run: |
          set -e
          # Self-healing: If strict fails, fallback to fix-lockfile and rerun
          pnpm install --frozen-lockfile || (pnpm install --fix-lockfile && pnpm install --frozen-lockfile)
        env:
          NODE_ENV: production

      # Run lint step with pnpm
      - id: lint
        name: Run Lint
        run: pnpm lint

      # Run tests step with pnpm
      - id: test
        name: Run Tests
        run: pnpm test -- --ci

      # Outcome detection for self-healing workflow
      - id: outcome
        run: |
          if [ "${{ steps.lint.outcome }}" = "success" ] && [ "${{ steps.test.outcome }}" = "success" ]; then
            echo "status=success" >> "$GITHUB_OUTPUT"
          else
            echo "status=failure" >> "$GITHUB_OUTPUT"
          fi

      # Optional: Security scan (enable if required; uncomment to use)
      # - name: pnpm audit
      #   run: pnpm audit

  revert_if_failed:
    needs: [ci]
    if: needs.ci.outputs.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: "master"
          fetch-depth: 0
      - name: Revert last commit on master
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git revert --no-edit "${GITHUB_SHA}" || exit 1
          git push origin HEAD:master

