name: enforce-main-health
on:
  push:
    branches: [master]
permissions:
  contents: write
  pull-requests: write
jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.outcome.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci || npm i
      - id: lint
        run: npm run lint
      - id: test
        run: npm test -- --ci
      - id: outcome
        run: |
          if [ "${{ steps.lint.outcome }}" = "success" ] && [ "${{ steps.test.outcome }}" = "success" ]; then
            echo "status=success" >> "$GITHUB_OUTPUT"
          else
            echo "status=failure" >> "$GITHUB_OUTPUT"
          fi

  revert_if_failed:
    needs: [ci]
    if: needs.ci.outputs.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "master"
          fetch-depth: 0
      - name: Revert last commit on master
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git revert --no-edit "${GITHUB_SHA}" || exit 1
          git push origin HEAD:master
