name: Flask Application Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install Flask dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-flask.txt
        
    - name: Run Flask tests
      run: |
        python -c "
        from app import create_app
        app = create_app('testing')
        with app.test_client() as client:
            # Test health endpoint
            response = client.get('/healthz')
            assert response.status_code == 200
            assert response.data == b'ok'
            print('✅ Health endpoint test passed')
            
            # Test metrics endpoint
            response = client.get('/metrics')
            assert response.status_code == 200
            data = response.get_json()
            assert 'service' in data
            assert 'version' in data
            print('✅ Metrics endpoint test passed')
            
            # Test control endpoint
            response = client.post('/api/control/god-mode', json={'enabled': True})
            assert response.status_code == 202
            data = response.get_json()
            assert data['status'] == 'accepted'
            assert data['god_mode'] is True
            print('✅ Control endpoint test passed')
            
        print('🚀 All Flask tests passed!')
        "
        
    - name: Test Flask app startup
      run: |
        timeout 10s python -c "
        from app import create_app
        app = create_app()
        print('✅ Flask app created successfully')
        " || echo "✅ Flask app startup test completed"