# .github/workflows/guardrails.yml
name: Guardrails
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  security-events: write
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Enforce signed commits
        run: |
          unsigned=$(git log --pretty='%H %G?' origin/${{ github.base_ref || 'HEAD' }}..HEAD | awk '$2!="G"')
          if [ -n "$unsigned" ]; then echo "Unsigned commits found"; echo "$unsigned"; exit 1; fi
      - name: Enforce Conventional Commits
        run: |
          npx --yes @commitlint/cli@19 -V --from=origin/${{ github.base_ref || 'HEAD' }} --to=HEAD
      - name: Secret scan (trufflehog)
        uses: trufflesecurity/trufflehog@3d1da2a8999f3a2f9ca8ad6cf73cdbbbc2e6f623  # trufflesecurity/trufflehog@v3
        with:
          path: .
          base: ${{ github.event.before || 'HEAD~1' }}
          head: HEAD
      - name: Python setup
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # actions/setup-python@v5
        with: {python-version: '3.11', cache: 'pip'}
      - run: pip install -r requirements.txt && pip install pytest pytest-asyncio pytest-cov bandit safety
      - name: Lint security
        run: |
          bandit -r platform -q || true
          safety check -r requirements.txt --full-report || true
      - name: Unit + integration tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
        run: |
          pytest -q --disable-warnings --maxfail=1
      - name: Container SBOM + scan
        uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a  # anchore/sbom-action@v0
      - name: Trivy FS
        uses: aquasecurity/trivy-action@6e7b396d6e8b019329bf2b557db1b18b45fd5b7d  # aquasecurity/trivy-action@master
        with: {scan-type: 'fs', scan-ref: '.'}
      - name: Require ADR/Docs on architectural changes
        run: |
          if git diff --name-only origin/${{ github.base_ref || 'HEAD' }}..HEAD | grep -E 'platform/(core|agents|database)|nginx/|monitoring/'; then
            git diff --name-only | grep -qE '^docs/|^ADR' || (echo "Missing docs/ADR for arch change" && exit 1)
          fi
