name: Order Processing Agent
permissions:
  contents: read
on:
  workflow_call: {}
  repository_dispatch:
    types: [product_research_complete, campaign_complete]
jobs:
  call:
    uses: ./.github/workflows/_reusable-base.yml
    with: { agent: "order_processing" }
