name: OSV-Scanner

on:
  pull_request:
    branches: [ master ]
  merge_group:
    branches: [ master ]
  schedule:
    - cron: '34 9 * * 6'
  push:
    branches: [ master ]

concurrency:
  group: osv-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78 # v1.7.1
    with:
      scan-args: |
        -r
        --skip-git
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78 # v1.7.1
    with:
      scan-args: |
        -r
        --skip-git
        ./
