name: trivy
on:
  push:
    branches: [master, main]
  pull_request:
permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  fs-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-files.sarif
          ignore-unfixed: true
          severity: HIGH,CRITICAL
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action@e2b3eafc8d227b0241d48be5f425d47c2d750a13  # github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-files.sarif
          category: trivy-fs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
